System/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('usuarios/', include('usuarios.urls')),
    path('usuarios/login/', auth_views.LoginView.as_view(), name='login'),
    path('admin/', admin.site.urls),

]

usuarios/urls.py
from  django.urls import path
from .import views

urlpatterns = [
    path('', views.index, name="index"),
    path('gerenciar-conta/', views.gerenciar_conta, name='gerenciar_conta'),
    path('gerenciar-conta/criar-conta/', views.criar_conta, name='criar_conta'),
    path('gerenciar-conta/editar-dados/<int:id_usuario>', views.editar_dados, name='editar_dados'),
    path('gerenciar-conta/deletar-conta/<int:id_usuario>', views.deletar_conta, name='deletar_conta'),
    path('gerenciar-conta/deletar-conta/confirmar-exclusao-dados/<int:id_usuario>', views.confirmar_exclusao_dados, name='confirmar_exclusao_dados'),
    
]

usuarios/models.py
from django.contrib.auth.models import User
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.core.validators import RegexValidator
from django.db.models.signals import post_save
from django.dispatch import receiver

class Usuario(User):
    cpf = models.CharField(max_length=11, unique=True, validators=[RegexValidator(regex='^\d{11}$', message='CPF inválido')], verbose_name="Infome seu CPF")
    telefone = PhoneNumberField(verbose_name="Telefone (99) 9999-9999")
    data_de_criacao = models.DateTimeField(auto_now_add=True)
    data_nascimento = models.DateField(null=True, blank=True)

    # Renomear os campos para evitar conflitos
    #grupos = models.ManyToManyField('auth.Group', related_name='usuario_grupos')
    #permissoes = models.ManyToManyField('auth.Permission', related_name='usuario_permissoes')



usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from .models import Usuario
from django.contrib.auth.models import User
from phonenumber_field.formfields import PhoneNumberField  # Corrected import
from phonenumber_field.widgets import PhoneNumberInternationalFallbackWidget


class UsuarioEditForm(UserChangeForm):
    class Meta:
        model = Usuario
        fields = ['username', 'email', 'cpf', 'telefone', 'data_nascimento']


class UsuarioForm(forms.ModelForm):

    username = forms.CharField(widget=forms.TextInput(attrs={"class": "username"}))
    password = forms.PasswordInput(attrs={"class": "password"})
    email = forms.EmailField(widget=forms.EmailInput(attrs={"class": "email"}))
    data_nascimento = forms.DateField(widget=forms.DateInput(attrs={"class": "data_nascimento"}))
    cpf = forms.CharField(widget=forms.TextInput(attrs={"class": "cpf"}))
    telefone = PhoneNumberField(widget=PhoneNumberInternationalFallbackWidget(attrs={'class': 'telefone'}))

    class Meta:
        model = Usuario
        fields = ['username', 'password', 'email', 'cpf', 'telefone', 'data_nascimento']  # Incluindo campos adicionais

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Nome de Usuário'
        

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if '@' not in email:
            raise forms.ValidationError('Endereço de email inválido.')
        return email

    def clean_cpf(self):
        cpf = self.cleaned_data.get('cpf')
        if len(cpf) != 11:
            raise forms.ValidationError('CPF deve ter 11 dígitos.')
        if Usuario.objects.filter(cpf=cpf).exists():
            raise forms.ValidationError('Este CPF já está em uso.')
        return cpf
 

    def clean_telefone(self):
        telefone = self.cleaned_data.get('telefone')
        if len(telefone) < 8:
            raise forms.ValidationError('Telefone deve ter no mínimo 8 dígitos.')
        return telefone

    def clean_username(self):
        username = self.cleaned_data.get('username')
        if len(username) < 3:
            raise forms.ValidationError('Nome de usuário deve ter no mínimo 3 caracteres.')
        return username

usuarios/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Usuario
from item.models import Item
from django.http import  HttpResponse, HttpResponseRedirect
from .forms import UsuarioEditForm, UsuarioForm
from django.core.exceptions import ValidationError



def index(request):
    itens = Item.objects.all()
    return render(request, "usuarios/index.html", {'itens': itens})

# Listar dados da CONTA
def gerenciar_conta(request):
    if request.user.is_authenticated:  # Verifica se o usuário está autenticado
        try:
            usuario = Usuario.objects.get(username=request.user)
        except Usuario.DoesNotExist:  # Trata o caso em que o usuário não possui um registro
            usuario = None  # Define o usuário como None para indicar que não há registro
        
        return render(request, 'usuarios/gerenciar-conta.html', {'usuario': usuario})
    else:
        # Se o usuário não está autenticado, não há registro
        return render(request, 'usuarios/gerenciar-conta.html', {'usuario': None})

# Criar CONTA
def criar_conta(request):
    if request.method == 'POST':
        form = UsuarioForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            
            # Cleaned(normalized) data
            password = form.cleaned_data['password']
            
            #  Use set_password here
            user.set_password(password)
            user.save()

            return redirect('login')
    else:
        form = UsuarioForm()
    return render(request, "registration/criar-conta.html", {'form': form})


# Editar dados da CONTA
@login_required
def editar_dados(request, id_usuario):
    usuario = get_object_or_404(Usuario, id=id_usuario)
    if request.method == 'POST':
        form = UsuarioEditForm(request.POST, instance=usuario)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/usuarios/gerenciar-conta/?mensagem=Salvo')
    else:
        form = UsuarioForm(instance=usuario)
    return render(request, 'usuarios/editar-dados.html', {'form': form, 'id_usuario':id_usuario})

# Excluir CONTA
@login_required
def deletar_conta(request, id_usuario):
    Usuario.objects.get(pk=id_usuario).delete()
    if Usuario.objects.count() == 0:
        return HttpResponseRedirect("/usuarios/login?mensagem=Deletado")  # Redireciona para a página de login
    return HttpResponseRedirect("/usuarios/gerenciar-conta?msg=Deletado")


@login_required

def confirmar_exclusao_dados(request, id_usuario):
    # Recupere o objeto Usuario com base no id_usuario
    usuario = get_object_or_404(Usuario, pk=id_usuario)

    if request.method == 'POST':
        usuario.delete()
        return redirect('index.html')  # Ou qualquer URL para onde você deseja redirecionar após a exclusão

    return render(request, 'usuarios/confirmar-exclusao-dados.html', {'usuario': usuario})


templates/usuarios/confirmar-exclusao-dados.html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../../static/css/style.css">
    <title>Gerenciar Conta</title>

    {% block topbar %}
    {% include "_topbar.html"%}
    {% endblock %}

</head>
<body>

    <div class="container2">

        <h3>Tem certeza que deseja apagar sua conta?</h3>
    
        <div class="table-responsive">
            <div class="table-columns">
                        <div class="table-column">
                            <div class="table-cell"><strong>Nome:</strong> {{ usuario.username }}</div>
                            <div class="table-cell"><strong>CPF:</strong> {{ usuario.cpf }}</div>
                            <div class="table-cell"><strong>E-mail:</strong> {{ usuario.email }}</div>
                            <div class="table-cell"><strong>Telefone:</strong> {{ usuario.telefone }}</div>
                            <div class="table-cell"><strong>Data de Nascimento:</strong> {{ usuario.data_nascimento }}</div>
                        </div>
                    <div class="table-column">
                        <div class="table-cell" colspan="2">
                            <a class="add" href="/usuarios/gerenciar-conta/deletar-conta/{{ usuario.id }}" >Sim</a>

                            
                            <a class="add" href="/usuarios/gerenciar-conta/">Não</a></div>
                    </div>
            </div>
        </div>
    
    </div>
    
        
    </div>

<footer class="footer_section">
    {% block footer %}
    {% include "_footer.html"%}
    {% endblock %}
</footer>

</body>
</html>


templates/usuarios/editar-dados.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/criar-conta.css' %}">
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css">
    <title>Editar Dados</title>

    {% block topbar %}
    {% include "_topbar.html" %}
    {% endblock %}
</head>
<body>
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="user_card1">
                <div class="d-flex justify-content-center form_container">
                    <form method="post" action="">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_username">Nome de Usuário:</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                                </div>
                                {{ form.username }}
                            </div>
                            {% for error in form.username.errors %}
                                <small class="form-text text-danger">{{ error }}</small>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="id_email">Endereço de Email:</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-envelope"></i></span>
                                </div>
                                {{ form.email }}
                            </div>
                            {% for error in form.email.errors %}
                                <small class="form-text text-danger">{{ error }}</small>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="id_cpf">CPF:</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-id-card"></i></span>
                                </div>
                                {{ form.cpf }}
                            </div>
                            {% for error in form.cpf.errors %}
                                <small class="form-text text-danger">{{ error }}</small>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="id_telefone">Telefone:</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-phone"></i></span>
                                </div>
                                {{ form.telefone }}
                            </div>
                            {% for error in form.telefone.errors %}
                                <small class="form-text text-danger">{{ error }}</small>
                            {% endfor %}
                        </div>
                        <div class="form-group">
                            <label for="id_data_nascimento">Data de Nascimento:</label>
                            <div class="input-group">
                                <div class="input-group-prepend">
                                    <span class="input-group-text"><i class="fas fa-calendar-alt"></i></span>
                                </div>
                                {{ form.data_nascimento }}
                            </div>
                            <small class="form-text text-danger">Formato da data: DD/MM/AAAA.</small>
                        </div>
                        <input type="submit" value="Editar" class="btn login_btn">
                    </form>
                </div>
            </div>
        </div>
    </div>

    <footer class="footer_section">
        {% block footer %}
        {% include "_footer.html" %}
        {% endblock %}
    </footer>

    <script>
        function togglePasswordVisibility(icon) {
            var passwordInput = icon.parentNode.querySelector('input');
            if (passwordInput.type === "password") {
                passwordInput.type = "text";
                icon.innerHTML = '<i class="fas fa-eye-slash"></i>';
            } else {
                passwordInput.type = "password";
                icon.innerHTML = '<i class="fas fa-eye"></i>';
            }
        }
    </script>
</body>
</html>

templates/usuarios/formClientes.html
{% extends '_base.html'%}

{% block content %}

<form action="/usuarios/criar-conta/" method="post">
    {%csrf_token %}
    {{form.as_p}}
    <br>
    <input type="submit" value="Enviar Dados">
</form>

{% endblock %}

templates/usuarios/gerenciar-conta.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Gerenciar Conta</title>

    {% block topbar %}
    {% include "_topbar.html" %}
    {% endblock %}
</head>
<body>

    <div class="container2">
        <div class="table-responsive">
            <div class="table-columns">
                {% if usuario %}
                    <div class="table-column">
                        <div class="table-cell"><strong>Nome:</strong> {{ usuario.username }}</div>
                        <div class="table-cell"><strong>CPF:</strong> {{ usuario.cpf }}</div>
                        <div class="table-cell"><strong>E-mail:</strong> {{ usuario.email }}</div>
                        <div class="table-cell"><strong>Telefone:</strong> {{ usuario.telefone }}</div>
                        <div class="table-cell"><strong>Data de Nascimento:</strong> {{ usuario.data_nascimento }}</div>
                        <div class="table-cell"><strong>Editar dados:</strong> <a class="linkamarelo" href="{% url 'editar_dados' usuario.id %}">Editar</a></div>
                        <div class="table-cell"><strong>Excluir conta:</strong> <a class="linkamarelo" href="{% url 'confirmar_exclusao_dados' usuario.id %}">Deletar</a></div>
                    </div>
                {% else %}
                    <div class="table-column">
                        <div class="table-cell" colspan="2">Não há registros</div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

<footer class="footer_section">
    {% block footer %}
    {% include "_footer.html" %}
    {% endblock %}
</footer>

</body>
</html>

templates/usuarios/index.html
{% extends '_base.html'%}